spring.application.name=msvc-historial-mantenimiento
server.port=8009

spring.datasource.url=jdbc:mysql://localhost:3306/msvc_lubrimax_historial_mantenimiento?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=adminMILDER1234@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true

clients.vehiculos.url=http://localhost:8008/api/vehiculos

logging.level.org.hibernate.SQL=debug
