spring.application.name=msvc-entrega-operador
server.port=8054

spring.datasource.url=jdbc:mysql://localhost:3306/db_entrega_operador?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=adminMILDER1234@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

services.operador-autorizado.url=http://localhost:8055
services.acopio-temporal.url=http://localhost:8053
