spring.application.name=msvc-orden-servicio
server.port=8010

spring.datasource.url=jdbc:mysql://localhost:3306/msvc_lubrimax_orden_servicio?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=adminMILDER1234@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true

clients.clientes.url=http://localhost:8004/api/clientes
clients.vehiculos.url=http://localhost:8008/api/vehiculos
clients.historial.url=http://localhost:8009/api/historiales

logging.level.org.hibernate.SQL=debug
