spring.application.name=msvc-orden-servicio
server.port=8040

spring.datasource.url=jdbc:mysql://localhost:3306/lubrimax_ordenes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=unc2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true

clients.clientes.url=http://localhost:8010/api/clientes
clients.vehiculos.url=http://localhost:8020/api/vehiculos
clients.historial.url=http://localhost:8030/api/historiales

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
