spring.application.name=msvc-ejecucion-mantenimiento
server.port=8011

spring.datasource.url=jdbc:mysql://localhost:3306/msvc_lubrimax_ejecucion_mantenimiento?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=adminMILDER1234@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

services.agenda-tecnico.url=http://localhost:8012
services.acopio-temporal.url=http://localhost:8013
services.orden-servicio.url=http://localhost:8010
